<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_K</name>
   <tag></tag>
   <elementGuidId>7b50320e-45f6-405d-bf1c-49399275a1e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-button-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-button-14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b1afe15-9bd9-41a3-9190-eca72a9bc952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-button-14</value>
      <webElementGuid>a5874dfb-4d2f-4911-9d7c-94ba2bd9e11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7983bf64-f1be-4ae7-9881-088cdbb8de13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>789b31a4-c55c-4a67-949f-fd127a40b4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-list-14</value>
      <webElementGuid>579a2b7f-c18c-428e-b78e-76fb12e29497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menu-button css-kya9f7</value>
      <webElementGuid>92f02c65-4381-45c3-95f9-9ceecfd97b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K</value>
      <webElementGuid>8b1f763e-ea62-4fbf-80fd-ff75905759d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-button-14&quot;)</value>
      <webElementGuid>fa775da9-2525-4285-8f12-622a14c6a803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-button-14']</value>
      <webElementGuid>445f57bd-d3eb-46b0-a0db-d43ee2987353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>9e1b9419-54a3-4901-8251-043a547c4cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>9fc34496-02c2-412b-82c1-c086ee53bad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>a7d8b386-b0ed-4388-b09e-5c9d23af2e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4c921cb5-b54f-4a3e-b9bf-033ae6ae6541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'menu-button-14' and (text() = 'K' or . = 'K')]</value>
      <webElementGuid>36a4abff-f82d-4077-ab99-04b1a7254951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
