<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_selectkategori</name>
   <tag></tag>
   <elementGuidId>db2a806f-8632-4612-8f46-4c11bc648a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'row' and @class = 'css-13n66qk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>fc873b24-98db-463f-bbaf-a835f9decc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13n66qk</value>
      <webElementGuid>fbd1adf0-cdf5-4206-9a6f-f4c97531f7b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
