<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_seacrhbykategoru</name>
   <tag></tag>
   <elementGuidId>f46ae5bf-e15a-47f4-8bc6-8b6e6f32cb0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-15</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
