<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LihatSemuaPromo</name>
   <tag></tag>
   <elementGuidId>b3ce85cb-fa82-44c2-8ed7-dec2dcf37c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Lihat Semua' or . = 'Lihat Semua') and @class = 'android.view.View']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementId</name>
      <type>Main</type>
      <value>00000000-0000-0164-0000-011a00000000</value>
      <webElementGuid>1d5aeef3-da70-415b-9225-923097b34a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Semua</value>
      <webElementGuid>67485c98-7f88-4ecd-a92d-08a7542608f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>bcad8018-3a8b-4122-b4a9-22d7ed0de074</webElementGuid>
   </webElementProperties>
</WebElementEntity>
