<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LihatSemua1</name>
   <tag></tag>
   <elementGuidId>b0c334f7-faa0-47d1-99f9-afc76e327f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'android.view.View' and (text() = 'Lihat Semua' or . = 'Lihat Semua') and @index = '13' and @elementId = '00000000-0000-0195-0000-01c500000001']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>d6bb9f9a-fbe5-481a-984d-ecc6caf51b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Semua</value>
      <webElementGuid>86e5a8e5-9071-4933-adbf-0e77102cb6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>d91c7ee5-2836-40a7-bff2-280c61f209f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementId</name>
      <type>Main</type>
      <value>00000000-0000-0195-0000-01c500000001</value>
      <webElementGuid>912a3518-fce0-45ad-810a-bd5fb43a4883</webElementGuid>
   </webElementProperties>
</WebElementEntity>
